# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Notepad++.Notepad++
PackageVersion: 8.6.3
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.3/npp.8.6.3.Installer.exe
  InstallerSha256: 367964AAAD658BC3FB947ACE5D10FCF439FC472C0B59F7EC95F2660B33A81AD4
  AppsAndFeaturesEntries:
  - DisplayName: Notepad++ (32-bit x86)
- Architecture: x64
  InstallerUrl: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.3/npp.8.6.3.Installer.x64.exe
  InstallerSha256: 1CDEE2049B249B2F7E9FEC2077A2599115733BCF1C9C2490154BD88192EA8104
  AppsAndFeaturesEntries:
  - DisplayName: Notepad++ (64-bit x64)
- Architecture: arm64
  InstallerUrl: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.3/npp.8.6.3.Installer.arm64.exe
  InstallerSha256: 5652E84D46BDE7362E6A4559657CAE3DB706BF512D150018EF7FE47891982700
  AppsAndFeaturesEntries:
  - DisplayName: Notepad++ (ARM 64-bit)
ManifestType: installer
ManifestVersion: 1.6.0
